#!/usr/bin/env node

const yargs = require('yargs')
const buildCommandLineInterface = require('../../index')

buildCommandLineInterface({
  version: '0.0.1',
  command: {
    handlers: [
      function(options) { console.log('Running default with option: ' + options.foo) }
    ],
    options: {
      foo: {
        description: 'Foo option',
        alias: 'f',
        demand: true,
        type: 'string',
      }
    }
  }
})

// Test examples

module.exports = [
  {
    description: 'Running default command without required option',
    command: './cli.js',
    code: 1,
    output: `
cli.js [options]

Options:
  --help, -h     Show help  [boolean]
  --version, -v  Show version  [boolean]
  --foo, -f      Foo option  [string] [required]

Missing required argument: foo
`
  },

  {
    description: 'Showing help message',
    commands: [
      './cli.js --help',
      './cli.js -h'
    ],
    code: 0,
    output: `
cli.js [options]

Options:
  --help, -h     Show help  [boolean]
  --version, -v  Show version  [boolean]
  --foo, -f      Foo option  [string] [required]
`
  },

  {
    description: 'Running default command with the required option',
    command: './cli.js --foo bar',
    code: 0,
    output: 'Running default with option: bar'
  },

  {
    description: 'Showing version message',
    commands: ['./cli.js --version', './cli.js -v'],
    code: 0,
    output: '0.0.1'
  }
]
