#!/usr/bin/env node

const yargs = require('yargs')
const buildCommandLineInterface = require('../../index')

buildCommandLineInterface({
  version: '0.0.1',
  command: {
    handlers: [
      function(options) { console.log('Running default with option: ' + options.foo) }
    ],
    options: {
      foo: {
        description: 'Foo option',
        alias: 'f',
        demand: true,
        type: 'string',
      }
    }
  }
})
